# kvstore-deployment-service-2.0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore-app-2-0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kvstore-app
      version: "2.0"
  template:
    metadata:
      labels:
        app: kvstore-app
        version: "2.0"
    spec:
      containers:
      - name: kvstore-app
        image: sinvalvm/kvstore:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http