[package]
name = "fibonacci"
version = "0.1.0"
authors = ["Sinval Vieira <sinvalneto01@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false